language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hedshogg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hedshogg/docker-react npm run test